name: CommandHelper
version: ${project.version}
main: net.testusuke.commandhelper.CommandHelper
api-version: 1.13
author: [testusuke]
commands:
  cmdhelp:
    permission: commandhelper.general
    permission-message: You don't have permission!

